### ISSUE TITLE
Php doc

### ISSUE THREAD

**Issue by septyaman** [ekaputra07/gempa-monitor#1]
Bro eka, ada document untuk php nggak ya? susah main py py :dango:

**Comment by ekaputra07** [comment]
@septyaman maksudnya PHP doc untuk apanya gan? mengenai PHP di appengine atau source gempa-monitor ini?

**Comment by septyaman** [comment]
Dokumentasi untuk apinya gan, kok disitus BMKG lkagak nemu ya... atau bagaimana teknik sebenarnya? bisa jelesin dikit bro?

**Comment by ekaputra07** [comment]
Itu dia gan di Indonesia ini data-data publik seperti ini jarang sekali ada API nya, jadi ya kita sendiri yang harus muter otak dikit :).

Untuk situs resminya ada disini gan: http://inatews.bmkg.go.id/new/ (tidak ada API tersedia :( )
jadi saya pakai data RSS nya (http://inatews.bmkg.go.id/rss/csvlast60event.txt) terdapat daftar 60 gempa terbaru yang terjadi, itu file masih dalam format CSV.

CSV itu saya parsing/extract datanya trus simpen aja ke DB, data itu trus di tampilin.
Biar selalu up-to date, saya jalanin cron di server untuk mengupdate DB dengan data terbaru dari link itu, klo saya setiap 6 jam (dengan asumsi tidak terlalu sering, tetapi juga biar selalu up-to-date).

gitu aja gan simple sebenarnya, ga ada teknik khusus.

**Comment by septyaman** [comment]
hheheehe kirain tadi ada APi nya toh. Tapi keren, keratif bangets bro.

**Comment by ekaputra07** [comment]
makasi gan, ini cuma proyek iseng2 aja, sapa tau berguna :)

**Comment by septyaman** [comment]
Good Job !
